#!/bin/bash
# Basic env init
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
exec 2>>"$CWD/../crash.log"
source "$CWD/../.env"
source "$CWD/../i18n.sh"

echo -n "{\
\"title\":\"$(T server_info_title)\",\
\"embeds\":[\
{\"title\":\"$(T connection_info_title)\",\"color\":12745742,\"fields\":[\
{\"name\":\"$(T server_name)\",\"value\": \"$VHSERVERNAME\"},\
{\"name\":\"$(T ip)\",\"value\": \"||$PUBLICIP:$VHSERVERPORT||\"},\
{\"name\":\"$(T password)\",\"value\": \"||$VHSERVERPASSWD||\"},\
{\"name\":\"$(T last_check)\",\"value\": \"$(date +'%F.%T')\"}\
]}\
]}"
