#!/bin/bash
# Basic env init
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
exec 2>>"$CWD/../crash.log"
source "$CWD/../.env"
# Update server status
"$VSSDIR/status/server-status" --for-webhook | "$CWD/webhook.json-sender" --status

# Output the last stdout logs if asked.
# If no message ID is set yet, we create the initial message once so the user can later copy the ID.
if [ "${SENDLASTLOGS:-0}" -gt 0 ] 2>/dev/null
then
  LAST_LOG="$(ls -1tr "$VALHEIMSERVERLOGPATH" 2>/dev/null | tail -1)"
  if [ -z "$LAST_LOG" ]
  then
    echo 'no log to send' >&2
  else
    tail -n "$SENDLASTLOGS" "$LAST_LOG" | sed ':a;N;$!ba;s/\n/\\n/g' | echo "{\"embeds\":[\
{\"title\":\"Last Logs\",\"color\":10181046,\"description\":\"$(</dev/stdin)\"}\
]}" | "$CWD/webhook.json-sender" "$LASTLOGMESSAGEID"
  fi
fi

# Output the server connection info if asked.
# If no message ID is set yet, we create the initial message so the user can later copy it.
if [ "${SENDSERVERCONNECTIONINFO:-0}" -gt 0 ] 2>/dev/null
then
  echo -n "{\
\"title\":\"Valheim server informations\",\
\"embeds\":[\
{\"title\":\"Connection\",\"color\":12745742,\"url\":\"$STATUSURL\",\"fields\":[\
{\"name\":\"Last Check\",\"value\": \"$(date +'%F.%T')\"},\
{\"name\":\"IP\",\"value\": \"||$PUBLICIP:$VHSERVERPORT||\"},\
{\"name\":\"Password\",\"value\": \"||$VHSERVERPASSWD||\"}\
]}\
]}" | "$CWD/webhook.json-sender" "$SERVERCONNECTIONINFOMESSAGEID"
fi

