#!/bin/bash
# author: laryakan, date 2021/03/12
# Basic env init
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source "$CWD/../.env"

# Stats
TOTALCPU=$(cat /proc/cpuinfo|grep processor|wc -l) # Cores
TOTALRAM=$(($(grep MemTotal /proc/meminfo|cut -d' ' -f9)/1024)) #(MB)
CPUUSAGE=$(($(top -p `pgrep valheim_server` -b -n1 | awk '{print $9}' | tail -n1 | cut -d'.' -f1) /$TOTALCPU))
RAMUSAGE=$(top -p $VALSERVERPID -b -n1 | awk '{print $10}' | tail -n1)

if [ "$1" = '--for-webhook' ]
then
	if [ -z "$VALSERVERPID" ]
	then
		echo -n "{\"embeds\":[{\"title\":\"offline\",\"color\":15158332,\"url\":\"$STATUSURL/\",\"fields\":[\
{\"name\":\"Last Check\",\"value\": \"$(date +'%F.%T')\"}\
]}]}"
		exit 1
	else
		LIGHTONLINELIST=$(cat $CONNECTEDPLAYERSFILE|cut -d';' -f2|sed 1d|sed ':a;N;$!ba;s/\n/, /g')
		LIGHTOFFLINELIST=$(cat $OFFLINEPLAYERSFILE|cut -d';' -f2|sed 1d|sed ':a;N;$!ba;s/\n/, /g')
		echo -n "{\
\"title\":\"Valheim server status\",\
\"embeds\":[\
{\"title\":\"online\",\"color\":3066993,\"url\":\"$STATUSURL/\",\"fields\":[\
{\"name\":\"Last Check\",\"value\": \"$(date +'%F.%T')\"},\
{\"name\":\"CPU\",\"value\": \"$CPUUSAGE%\",\"inline\":true},\
{\"name\":\"RAM\",\"value\": \"$RAMUSAGE%\",\"inline\":true},\
{\"name\":\"Online\",\"value\": \"${LIGHTONLINELIST:-nobody}\"},\
{\"name\":\"Offline\",\"value\": \"${LIGHTOFFLINELIST:-nobody}\"}\
]}\
]}"
	fi
	exit 0
fi


echo -e ">=VALHEIM SERVER STATUS @ `date +'%F.%T'`=<"
if [ -z "$VALSERVERPID" ]
then
	echo -e "SERVER OFFLINE !"
	exit 1
else
	echo -e "SERVER ONLINE !"
fi

echo -e "\n**Server session running since**"
ps -p $VALSERVERPID -o lstart,etime

echo -e "\n**Server consumption**"
echo -e "CPU ($TOTALCPU cores) : $CPUUSAGE%"
echo -e "RAM ($TOTALRAM MB) : $RAMUSAGE%"

echo -e "\n**Connected players**"
cat "$CONNECTEDPLAYERSFILE"

echo -e "\n**Offline players**"
cat "$OFFLINEPLAYERSFILE"
